<?php
/**
 * ElectroSuite Reseller States: Italy Provinces
 *
 * @author 		ElectroSuite
 * @category 	Core
 * @package 	ElectroSuite Reseller/Library
 * @version 	0.0.1
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $states;

$states['IT'] = array(
	'AG'    => __( 'Agrigento', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AL' => __( 'Alessandria', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AN' => __( 'Ancona', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AO' => __( 'Aosta', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AR' => __( 'Arezzo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AP' => __( 'Ascoli Piceno', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AT' => __( 'Asti', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AV' => __( 'Avellino', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BA' => __( 'Bari', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BT' => __( 'Barletta-Andria-Trani', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BL' => __( 'Belluno', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BN' => __( 'Benevento', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BG' => __( 'Bergamo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BI' => __( 'Biella', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BO' => __( 'Bologna', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BZ' => __( 'Bolzano', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BS' => __( 'Brescia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'BR' => __( 'Brindisi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CA' => __( 'Cagliari', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CL' => __( 'Caltanissetta', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CB' => __( 'Campobasso', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CI' => __( 'Carbonia-Iglesias', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CE' => __( 'Caserta', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CT' => __( 'Catania', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CZ' => __( 'Catanzaro', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CH' => __( 'Chieti', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CO' => __( 'Como', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CS' => __( 'Cosenza', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CR' => __( 'Cremona', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'KR' => __( 'Crotone', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'CN' => __( 'Cuneo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'EN' => __( 'Enna', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'FM' => __( 'Fermo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'FE' => __( 'Ferrara', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'FI' => __( 'Firenze', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'FG' => __( 'Foggia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'FC' => __( 'Forlì-Cesena', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'FR' => __( 'Frosinone', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'GE' => __( 'Genova', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'GO' => __( 'Gorizia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'GR' => __( 'Grosseto', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'IM' => __( 'Imperia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'IS' => __( 'Isernia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SP' => __( 'La Spezia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'AQ' => __( 'L&apos;Aquila', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'LT' => __( 'Latina', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'LE' => __( 'Lecce', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'LC' => __( 'Lecco', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'LI' => __( 'Livorno', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'LO' => __( 'Lodi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'LU' => __( 'Lucca', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MC' => __( 'Macerata', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MN' => __( 'Mantova', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MS' => __( 'Massa-Carrara', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MT' => __( 'Matera', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'ME' => __( 'Messina', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MI' => __( 'Milano', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MO' => __( 'Modena', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'MB' => __( 'Monza e della Brianza', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'NA' => __( 'Napoli', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'NO' => __( 'Novara', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'NU' => __( 'Nuoro', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'OT' => __( 'Olbia-Tempio', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'OR' => __( 'Oristano', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PD' => __( 'Padova', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PA' => __( 'Palermo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PR' => __( 'Parma', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PV' => __( 'Pavia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PG' => __( 'Perugia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PU' => __( 'Pesaro e Urbino', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PE' => __( 'Pescara', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PC' => __( 'Piacenza', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PI' => __( 'Pisa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PT' => __( 'Pistoia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PN' => __( 'Pordenone', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PZ' => __( 'Potenza', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'PO' => __( 'Prato', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RG' => __( 'Ragusa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RA' => __( 'Ravenna', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RC' => __( 'Reggio Calabria', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RE' => __( 'Reggio Emilia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RI' => __( 'Rieti', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RN' => __( 'Rimini', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RM' => __( 'Roma', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'RO' => __( 'Rovigo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SA' => __( 'Salerno', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VS' => __( 'Medio Campidano', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SS' => __( 'Sassari', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SV' => __( 'Savona', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SI' => __( 'Siena', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SR' => __( 'Siracusa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'SO' => __( 'Sondrio', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TA' => __( 'Taranto', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TE' => __( 'Teramo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TR' => __( 'Terni', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TO' => __( 'Torino', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'OG' => __( 'Ogliastra', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TP' => __( 'Trapani', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TN' => __( 'Trento', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TV' => __( 'Treviso', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'TS' => __( 'Trieste', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'UD' => __( 'Udine', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VA' => __( 'Varese', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VE' => __( 'Venezia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VB' => __( 'Verbano-Cusio-Ossola', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VC' => __( 'Vercelli', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VR' => __( 'Verona', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VV' => __( 'Vibo Valentia', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VI' => __( 'Vicenza', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
    'VT' => __( 'Viterbo', ELECTROSUITE_RESELLER_TEXT_DOMAIN )
);