<?php
/**
 * ElectroSuite Reseller States: Japan
 *
 * @author 		ElectroSuite
 * @category 	Core
 * @package 	ElectroSuite Reseller/Library
 * @version 	0.0.1
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

global $states;

$states['JP'] = array(
	'JP01' => __( 'Hokkaido', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP02' => __( 'Aomori', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP03' => __( 'Iwate', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP04' => __( 'Miyagi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP05' => __( 'Akita', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP06' => __( 'Yamagata', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP07' => __( 'Fukushima', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP08' => __( 'Ibaraki', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP09' => __( 'Tochigi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP10' => __( 'Gunma', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP11' => __( 'Saitama', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP12' => __( 'Chiba', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP13' => __( 'Tokyo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP14' => __( 'Kanagawa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP15' => __( 'Niigata', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP16' => __( 'Toyama', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP17' => __( 'Ishikawa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP18' => __( 'Fukui', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP19' => __( 'Yamanashi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP20' => __( 'Nagano', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP21' => __( 'Gifu', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP22' => __( 'Shizuoka', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP23' => __( 'Aichi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP24' => __( 'Mie', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP25' => __( 'Shiga', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP26' => __( 'Kyouto', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP27' => __( 'Osaka', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP28' => __( 'Hyougo', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP29' => __( 'Nara', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP30' => __( 'Wakayama', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP31' => __( 'Tottori', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP32' => __( 'Shimane', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP33' => __( 'Okayama', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP34' => __( 'Hiroshima', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP35' => __( 'Yamaguchi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP36' => __( 'Tokushima', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP37' => __( 'Kagawa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP38' => __( 'Ehime', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP39' => __( 'Kochi', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP40' => __( 'Fukuoka', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP41' => __( 'Saga', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP42' => __( 'Nagasaki', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP43' => __( 'Kumamoto', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP44' => __( 'Oita', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP45' => __( 'Miyazaki', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP46' => __( 'Kagoshima', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
	'JP47' => __( 'Okinawa', ELECTROSUITE_RESELLER_TEXT_DOMAIN ),
);
